In [3]:
import numpy as np
import pickle
from pathlib import Path

from tensorflow.keras.models import load_model

from model_helper import *
from DeepRouteSetHelper import *

## 1. Load in dataset

### 1-1. load original dataset

In [3]:
cwd = Path().cwd()
raw_path = cwd.parent / 'out' / 'DeepRouteSet_medium_out'

In [12]:
with open(raw_path, 'rb') as f:
    raw_gen_set = pickle.load(f)

raw_gen_set[next(iter(raw_gen_set))]

array([[ 8.        ,  2.        ,  4.        ,  0.        ],
       [ 9.        , 12.        , 15.        , 17.        ],
       [ 1.        ,  0.        ,  1.        ,  0.        ],
       [ 6.        ,  8.        ,  4.        ,  5.        ],
       [ 4.        ,  8.        ,  2.        ,  4.        ],
       [ 5.        ,  9.        , 12.        , 15.        ],
       [ 5.        ,  6.        ,  8.        ,  4.        ],
       [ 4.        , -6.        ,  2.        , -4.        ],
       [ 4.        ,  3.        ,  3.        ,  2.        ],
       [ 4.        ,  4.        ,  8.        ,  2.        ],
       [ 5.        ,  5.        ,  9.        , 12.        ],
       [ 3.        ,  5.        ,  6.        ,  8.        ],
       [ 4.        , -2.        , -4.        , -2.        ],
       [ 4.        ,  7.        ,  6.        ,  5.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.

In [11]:
raw_gen_set[next(iter(raw_gen_set))].shape

(22, 4)

### 1-2. Preprocessing and normalization

In [13]:
generated_routes = prepare_generated_data_for_grading(raw_gen_set, cwd.parent / 'preprocessing' / 'test_set_medium_gen_v1')

In [15]:
X = generated_routes['X']
X[0]

array([[ 0.96023916, -0.20666924,  1.        ,  0.83047469, -0.33863505,
        -1.18747248,  0.35784683,  1.2988742 ,  0.98080324, -0.33863505,
        -1.18747248, -0.5874089 ,  1.2988742 ,  0.98080324,  0.        ,
         0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
         0.        , -0.7745323 ],
       [-0.98807215,  0.52893319,  0.        ,  1.77573042,  0.96023916,
        -0.20666924,  0.83047469, -1.9483113 ,  0.73560243, -0.33863505,
        -1.18747248,  0.35784683, -0.6494371 ,  1.71640567,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        , -0.92370471],
       [-0.33863505,  1.26453562,  1.        , -0.11478103, -0.98807215,
         0.52893319,  1.77573042,  0.6494371 ,  0.73560243,  0.96023916,
        -0.20666924,  0.83047469, -1.2988742 ,  1.47120486,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        , -0.02120677],
       [-1.63750925

In [17]:
X.shape

(65, 12, 22)

## 2. Define GradeNet Model

In [8]:
GradeNet = load_model(cwd / 'GradeNet')

## 3. Make prediction on generated routes

In [8]:
X_pred = GradeNet.predict(X).argmax(axis = 1)

In [9]:
X_pred

array([2, 1, 1, 2, 2, 3, 2, 2, 3, 1, 2, 2, 3, 4, 0, 1, 5, 0, 0, 1, 2, 2,
       2, 3, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 5, 3, 0, 1, 0,
       2, 4, 0, 2, 1, 1, 1, 4, 3, 1, 2, 1, 1, 3, 2, 4, 2, 2, 4, 2, 1])

## 4. Plot out output and predicted grade

In [10]:
seq_raw_path = cwd.parent / 'out' / 'DeepRouteSet_medium_out_seq'
with open(seq_raw_path, 'rb') as f:
    gen_seq_raw = pickle.load(f)

In [ ]:
for i, route in enumerate(gen_seq_raw):
    print('Key = ' + generated_routes['keys'][i])
    print('V grade = ' + convert_num_to_V_grade(X_pred[i]))
    plotAProblem(route, 
                 title = 'Key = ' + generated_routes['keys'][i] + '/ V grade = ' + convert_num_to_V_grade(X_pred[i]), key = generated_routes['keys'][i], 
                 save = True)